<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="qasimsobeh-lt" name="CSVloginIOS" tests="1" failures="1" timestamp="18 Dec 2017 19:45:56 GMT" time="15.061" errors="0">
  <testcase name="test" time="12.772" classname="automationAssignment.CSVloginIOS">
    <failure type="com.experitest.client.InternalException" message="Exception caught while executing startLoggingDevice: Failed to start logging for device: iPhone 4. see SeeTest log for details">
      <![CDATA[com.experitest.client.InternalException: Exception caught while executing startLoggingDevice: Failed to start logging for device: iPhone 4. see SeeTest log for details
	at com.experitest.client.JavaClientInternals.executeInternally(JavaClientInternals.java:249)
	at com.experitest.client.Client.execute(Client.java:247)
	at com.experitest.client.Client.startLoggingDevice(Client.java:2266)
	at automationAssignment.CSVloginIOS.loginTestIOS(CSVloginIOS.java:38)
	at automationAssignment.CSVloginIOS.testAux(CSVloginIOS.java:26)
	at automationAssignment.BaseTest.test(BaseTest.java:120)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- CSVloginIOS -->
